apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-demo-service-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: prometheus-demo-label
  endpoints:
    - port: web