apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-svc
  labels:
    app: prometheus-demo-label
spec:
  selector:
    app: prometheus-demo-label
  ports:
    - port: 8080
      name: web
  type: NodePort