apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-demo-label
  name: prometheus-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-demo-label
  template:
    metadata:
      labels:
        app: prometheus-demo-label
    spec:
      containers:
      - name: prometheus-demo-container
        image: shahincsejnu/prometheus-demo:v1.0.1
        ports:
        - name: web
          containerPort: 8080